name: Run Pytest

on:
  push:
    branches:
      - from_perplexity
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: |
        pytest --cov=. --cov-report=term-missing
        pytest --verbose --disable-warnings